export const COMMENTS_FETCH = 'COMMENTS_FETCH';
export const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
export const COMMENTS_FETCH_FAIL = 'COMMENTS_FETCH_FAIL';
export const COMMENTS_ERROR_RESET = 'COMMENTS_ERROR_RESET';
export const COMMENTS_CREATE = 'COMMENTS_CREATE';
export const COMMENTS_CREATE_SUCCESS = 'COMMENTS_CREATE_SUCCESS';
export const COMMENTS_CREATE_FAIL = 'COMMENTS_CREATE_FAIL';
export const COMMENTS_INPUT_CHANGE = 'COMMENTS_INPUT_CHANGE';